name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  ## New Contributors

  $NEW_CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '🚨 Breaking Changes'
    semver-increment: 'major'
    exclusive: true
    when:
      conventional:
        breaking: true
      labels:
        - 'breaking-change'
  - title: '✨ Features'
    semver-increment: 'minor'
    exclusive: true
    when:
      conventional:
        type: 'feat'
      labels:
        - 'feature'
  - title: '⬆️ Dependency Updates'
    semver-increment: 'patch'
    exclusive: true
    when:
      conventional:
        scopes:
          - 'deps'
          - 'deps-dev'
        types:
          - 'build'
          - 'chore'
          - 'ci'
          - 'fix'
      labels:
        - 'dependencies'
    collapse-after: 5
  - title: '🐛 Bug Fixes'
    semver-increment: 'patch'
    exclusive: true
    when:
      conventional:
        type: 'fix'
      labels:
        - 'bug'
  - title: '🧰 Maintenance'
    semver-increment: 'patch'
    exclusive: true
    when:
      conventional:
        types:
          - 'build'
          - 'chore'
          - 'ci'
          - 'perf'
          - 'refactor'
          - 'revert'
          - 'style'
          - 'test'
      labels:
        - 'maintenance'
  - title: '📚 Documentation'
    semver-increment: 'patch'
    exclusive: true
    when:
      conventional:
        type: 'docs'
      labels:
        - 'documentation'
  - title: 'Other changes'
  - type: 'pre-exclude'
    when:
      label: 'skip-changelog'
