name: Release

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    name: Build backend image
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      context: backend
      cache: true
      meta-images: ghcr.io/${{ github.repository }}/backend
      meta-tags: |
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha,prefix=sha-,format=short
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-frontend:
    name: Build frontend image
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      context: frontend
      cache: true
      meta-images: ghcr.io/${{ github.repository }}/frontend
      meta-tags: |
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha,prefix=sha-,format=short
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-all-in-one:
    name: Build all-in-one image
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      context: .
      file: all-in-one/Dockerfile
      cache: true
      meta-images: ghcr.io/${{ github.repository }}/all-in-one
      meta-tags: |
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha,prefix=sha-,format=short
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
